production/urls.py
from django.urls import path

from production.views import (
    index,
    WorkerDetailView,
    WorkerCreateView,
    WorkerDeleteView,
    WorkerPhoneView,
    WorkerListView,
    WorkplaceListView,
    WorkplaceCreateView,
    WorkplaceUpdateView,
    WorkplaceDetailView,
    WorkplaceDeleteView,
    MaterialListView,
    MaterialDetailView,
    MaterialCreateView,
    MaterialUpdateView,
    MaterialDeleteView,
    PrinterListView,
    PrinterCreateView,
    PrinterDetailView,
    PrinterDeleteView,
    PrintQueueDetailView,
    PrintQueueListView,
    PrinterUpdateView,
    OrderDetailView,
    OrderListView,
    PrintQueueDeleteView,
    PrintQueueCreateView,
    PrintQueueUpdateView,
    change_order_status,
    OrderDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail",
    ),
    path(
        "workers/<int:pk>/phone/",
        WorkerPhoneView.as_view(),
        name="worker-phone",
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list",
    ),
    path(
        "workplaces/",
        WorkplaceListView.as_view(),
        name="workplace-list",
    ),
    path("workplaces/create/", WorkplaceCreateView.as_view(), name="workplace-create"),
    path(
        "workplaces/<int:pk>",
        WorkplaceDetailView.as_view(),
        name="workplace-detail",
    ),
    path(
        "workplaces/<int:pk>/update/",
        WorkplaceUpdateView.as_view(),
        name="workplace-update",
    ),
    path(
        "workplaces/<int:pk>/delete/",
        WorkplaceDeleteView.as_view(),
        name="workplace-delete",
    ),
    path(
        "materials/",
        MaterialListView.as_view(),
        name="material-list",
    ),
    path(
        "materials/<int:pk>/",
        MaterialDetailView.as_view(),
        name="material-detail",
    ),
    path("materials/create/", MaterialCreateView.as_view(), name="material-create"),
    path(
        "materials/<int:pk>/update/",
        MaterialUpdateView.as_view(),
        name="material-update",
    ),
    path(
        "materials/<int:pk>/delete/",
        MaterialDeleteView.as_view(),
        name="material-delete",
    ),
    path(
        "printers/",
        PrinterListView.as_view(),
        name="printer-list",
    ),
    path(
        "printers/<int:pk>/",
        PrinterDetailView.as_view(),
        name="printer-detail",
    ),
    path(
        "printers/create/",
        PrinterCreateView.as_view(),
        name="printer-create",
    ),
    path(
        "printers/<int:pk>/update/",
        PrinterUpdateView.as_view(),
        name="printer-update",
    ),
    path(
        "printers/<int:pk>/delete/",
        PrinterDeleteView.as_view(),
        name="printer-delete",
    ),
    path(
        "print-queues/",
        PrintQueueListView.as_view(),
        name="print-queue-list",
    ),
    path(
        "workplaces/<int:pk>/print-queue-create",
        PrintQueueCreateView.as_view(),
        name="print-queue-create",
    ),
    path(
        "print-queues/<int:pk>/update/",
        PrintQueueUpdateView.as_view(),
        name="print-queue-update",
    ),
    path(
        "print-queues/<int:pk>",
        PrintQueueDetailView.as_view(),
        name="print-queue-detail",
    ),
    path(
        "print-queues/<int:pk>/delete/",
        PrintQueueDeleteView.as_view(),
        name="print-queue-delete",
    ),
    path(
        "orders/<int:pk>/",
        OrderDetailView.as_view(),
        name="order-detail",
    ),
    path(
        "orders/<int:pk>/change-status",
        change_order_status,
        name="change-order-status",
    ),
    path(
        "orders/",
        OrderListView.as_view(),
        name="order-list",
    ),
    path(
        "orders/<int:pk>/delete/",
        OrderDeleteView.as_view(),
        name="order-delete",
    ),
]

app_name = "production"

wallis/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    # bild-in django authorization
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("production.urls", namespace="production")),
] + debug_toolbar_urls()

templates/includes/crispy_form.html
{% load crispy_forms_filters %}
<br>
<div>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <div>
      <button
          class="btn btn-primary"
          type="submit"
          name="approve"
      >
        Submit
      </button>
    </div>
  </form>
</div>

templates/includes/delete_form.html
<form action="" method="post">
  {% csrf_token %}
  <div class="d-flex justify-content-center">
    <input type="submit" name="confirm" value="Yes" class="btn btn-danger m-2">
    <input type="submit" name="cancel" value="No" class="btn btn-primary m-2">
  </div>
</form>

templates/includes/filter_form.html
<div>
  <div class="card">
    <div class="card-body">
      <form method="get">
        <div class="text-center form-inline mb-2">
          {% for field in filter.form %}
            <div class="form-inline">
              <label class="text-secondary mr-3" for="{{ field.id_for_label }}">{{ field.label }}</label>
              <div class="mr-4">{{ field }}</div>
            </div>
          {% endfor %}
        </div>
        <div class="text-center">
          <button type="submit"
                  class="btn btn-sm btn-default"
          ><i class="material-icons">search</i> Apply Filter
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

templates/includes/footer.html
<footer class="footer">
  <div class="container-fluid">
    <nav class="float-left">
      <ul>

        <li>
          <a target="_blank" rel="noopener noreferrer"
             href="https://github.com/vsafian/wallis">
            &copy;Wallis
          </a>
        </li>

      </ul>
    </nav>
    <div class="copyright float-right">
      coded by <a rel="noopener noreferrer" href="https://github.com/vsafian">VSafian</a>
    </div>
  </div>
</footer>

templates/includes/form.html
<hr>
<div class="form">
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <div>
      {{ form.non_field_errors }}
    </div>
    {% for field in form %}
      <div class="mb-3">
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
          <div>
            <br>
            {{ field.help_text }}
          </div>
        {% endif %}
        {% if field.errors %}
          <div class="text-danger">
            {% for error in field.errors %}
              <div class="list-unstyled">
                {{ error }}
              </div>
            {% endfor %}
          </div>
        {% endif %}
      </div>
    {% endfor %}
    <div>
      <button
          class="btn btn-primary"
          type="submit"
          name="approve">Submit
      </button>
    </div>
  </form>
</div>

templates/includes/navigation.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top">
  <div class="container-fluid">
    <div class="navbar-wrapper justify-content-start">
      <a class="navbar-brand" href={% url 'production:index' %}>
        Wallis
      </a>
    </div>
    {% if search_form %}
      <div class="navbar-wrapper navbar-collapse justify-content-end">
        {% include "includes/search_form.html" %}
      </div>
    {% endif %}
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link" href="{{ user.get_absolute_url }}" id="navbarDropdownProfile" data-toggle="dropdown"
             aria-haspopup="true"
             aria-expanded="false">
            <i class="material-icons">person</i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
            <a class="dropdown-item" href="{{ user.get_absolute_url }}">Profile</a>
            <div class="dropdown-divider"></div>
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <label class="dropdown-item dropdown-form-label">
                <input class="dropdown-form-input p-0" type="submit" value="Logout">
              </label>
            </form>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load query-transform %}
{% if is_paginated %}
  <div class="pagination d-flex justify-content-center align-content-center m-0">
    <ul class="list-unstyled d-flex">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link bg-secondary text-white h3 m-2" 
             href="?{% query_transform request page=page_obj.previous_page_number %}"
             title="Previous page"
          ><</a>
        </li>
      {% endif %}
      <li class="page-item">
        <span class="page-link text-dark h3 m-2">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link bg-secondary text-white h3 m-2" 
             href="?{% query_transform request page=page_obj.next_page_number %}"
             title="Next page" 
          >></a>
        </li>
      {% endif %}
    </ul>
  </div>
{% endif %}

templates/includes/scripts-sidebar.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');

        $sidebar_img_container = $sidebar.find('.sidebar-background');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

        if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
          if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
            $('.fixed-plugin .dropdown').addClass('open');
          }

        }

        $('.fixed-plugin a').click(function(event) {
          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .active-color span').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-color', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data-color', new_color);
          }
        });

        $('.fixed-plugin .background-color .badge').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('background-color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-background-color', new_color);
          }
        });

        $('.fixed-plugin .img-holder').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).parent('li').siblings().removeClass('active');
          $(this).parent('li').addClass('active');


          var new_image = $(this).find("img").attr('src');

          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            $sidebar_img_container.fadeOut('fast', function() {
              $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
              $sidebar_img_container.fadeIn('fast');
            });
          }

          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $full_page_background.fadeOut('fast', function() {
              $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
              $full_page_background.fadeIn('fast');
            });
          }

          if ($('.switch-sidebar-image input:checked').length == 0) {
            var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
          }
        });

        $('.switch-sidebar-image input').change(function() {
          $full_page_background = $('.full-page-background');

          $input = $(this);

          if ($input.is(':checked')) {
            if ($sidebar_img_container.length != 0) {
              $sidebar_img_container.fadeIn('fast');
              $sidebar.attr('data-image', '#');
            }

            if ($full_page_background.length != 0) {
              $full_page_background.fadeIn('fast');
              $full_page.attr('data-image', '#');
            }

            background_image = true;
          } else {
            if ($sidebar_img_container.length != 0) {
              $sidebar.removeAttr('data-image');
              $sidebar_img_container.fadeOut('fast');
            }

            if ($full_page_background.length != 0) {
              $full_page.removeAttr('data-image', '#');
              $full_page_background.fadeOut('fast');
            }

            background_image = false;
          }
        });

        $('.switch-sidebar-mini input').change(function() {
          $body = $('body');

          $input = $(this);

          if (md.misc.sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            md.misc.sidebar_mini_active = false;

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

          } else {

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

            setTimeout(function() {
              $('body').addClass('sidebar-mini');

              md.misc.sidebar_mini_active = true;
            }, 300);
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);

        });
      });
    });
  </script>
  

templates/includes/scripts.html
{% load static %}

<!--   Core JS Files   -->
  <script src="/static/assets/js/core/jquery.min.js"></script>
  <script src="/static/assets/js/core/popper.min.js"></script>
  <script src="/static/assets/js/core/bootstrap-material-design.min.js"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!-- Plugin for the momentJs  -->
  <script src="/static/assets/js/plugins/moment.min.js"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="/static/assets/js/plugins/sweetalert2.js"></script>
  <!-- Forms Validations Plugin -->
  <script src="/static/assets/js/plugins/jquery.validate.min.js"></script>
  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="/static/assets/js/plugins/jquery.bootstrap-wizard.js"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="/static/assets/js/plugins/bootstrap-selectpicker.js"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="/static/assets/js/plugins/bootstrap-datetimepicker.min.js"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="/static/assets/js/plugins/jquery.dataTables.min.js"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="/static/assets/js/plugins/bootstrap-tagsinput.js"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="/static/assets/js/plugins/jasny-bootstrap.min.js"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="/static/assets/js/plugins/fullcalendar.min.js"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="/static/assets/js/plugins/jquery-jvectormap.js"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="/static/assets/js/plugins/nouislider.min.js"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
  <!-- Library for adding dinamically elements -->
  <script src="/static/assets/js/plugins/arrive.min.js"></script>
  <!-- Chartist JS -->
  <script src="/static/assets/js/plugins/chartist.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/static/assets/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
  <!-- Custom -->
  {% if request.resolver_match.url_name == "index" %}
    <script src="{% static '/assets/js/index-st.js' %}"></script>
  {% endif %}
  
  

templates/includes/search_form.html
{% load crispy_forms_filters %}
<form method="get" action="" class="search navbar-wrapper form-inline">
  {{ search_form|crispy }}
  <button 
      type="submit" 
      class="page-link text-secondary border-0">
    <i class="material-icons">search</i>
  </button>
</form>

templates/includes/sidebar.html
<div class="sidebar" data-color="purple" data-background-color="white" data-image="/static/assets/img/sidebar-1.jpg">
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item {% if 'index' in segment %} active {% endif %}">
        <a class="nav-link" href="/">
          <i class="material-icons">store</i>
          <p>Home</p>
        </a>
        <hr>
      </li>
      <li class="nav-item {% if 'page-user' in segment %} active {% endif %}">
        <a class="nav-link" href="{{ user.get_absolute_url }}">
          <i class="material-icons">person</i>
          <p>User: {{ user.get_username }}</p>
        </a>
      </li>
      <li class="nav-item {% if 'ui-notifications' in segment %} active {% endif %}">
        <form class="nav-link" method="POST" action="{% url 'logout' %}">
          {% csrf_token %}
          <label class="nav-form-label">
            <i class="material-icons">directions_run</i>
            <input class="nav-form-input" type="submit" value="Logout">
          </label>
        </form>
      </li>
    </ul>
    <hr>
    {% if user.workplace %}
      <ul class="nav">
        <li class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
          <a class="nav-link" href="{% url 'production:workplace-detail' pk=user.workplace.id %}">
            <i class="material-icons">add</i>
            <p>{{ user.workplace.name }}</p>
          </a>
        </li>
      </ul>
      <hr>
    {% endif %}
    <ul class="nav">
      <li class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
        <a class="nav-link" href="{% url 'production:order-list' %}">
          <i class="material-icons">library_books</i>
          <p>Orders</p>
        </a>
      </li>

      <li class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
        <a class="nav-link" href="{% url 'production:worker-list' %}">
          <i class="material-icons">people</i>
          <p>Workers</p>
        </a>
      </li>
      <li class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
        <a class="nav-link" href="{% url 'production:workplace-list' %}">
          <i class="material-icons">work</i>
          <p>Workplaces</p>
        </a>
      </li>
      <li class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
        <a class="nav-link" href="{% url 'production:material-list' %}">
          <i class="material-icons">bubble_chart</i>
          <p>Materials</p>
        </a>
      </li>
      <li class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
        <a class="nav-link" href="{% url 'production:printer-list' %}">
          <i class="material-icons">print</i>
          <p>Printers</p>
        </a>
      </li>
      <li class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
        <a class="nav-link" href="{% url 'production:print-queue-list' %}">
          <i class="material-icons">tabs</i>
          <p>Print Queues</p>
        </a>
      </li>
    </ul>
  </div>
</div>

templates/includes/summary.html
<div id="summary">
  <hr>
  <h3>Summary:</h3>
  <div>
    <p><strong>Total Tiles:</strong> <span id="total-tiles">{{ summary.total_tiles }}</span></p>
    <p><strong>Total Area:</strong> <span id="total-area">{{ summary.total_area }}</span> m²</p>
    <p><strong>Winding left:</strong> <span id="winding-left">{{ summary.winding_left }}</span> m²</p>
  </div>
  {% if summary.messages %}
    <div class="text-warning row-form-errors mt-3">
      {% for message in summary.messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
</div>