production/urls.py
from django.urls import path

from production.views import (
    index,
    WorkerDetailView,
    WorkerCreateView,
    WorkerDeleteView,
    WorkerPhoneView,
    WorkerListView,
    WorkplaceListView,
    WorkplaceCreateView,
    WorkplaceUpdateView,
    WorkplaceDetailView,
    WorkplaceDeleteView,
    MaterialListView,
    MaterialDetailView,
    MaterialCreateView,
    MaterialUpdateView,
    MaterialDeleteView,
    PrinterListView,
    PrinterCreateView,
    PrinterDetailView,
    PrinterDeleteView,
    PrintQueueDetailView,
    PrintQueueListView,
    PrinterUpdateView,
    OrderDetailView,
    OrderListView,
    PrintQueueDeleteView,
    PrintQueueCreateView,
    PrintQueueUpdateView,
    change_order_status,
    OrderDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail",
    ),
    path(
        "workers/<int:pk>/phone/",
        WorkerPhoneView.as_view(),
        name="worker-phone",
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list",
    ),
    path(
        "workplaces/",
        WorkplaceListView.as_view(),
        name="workplace-list",
    ),
    path("workplaces/create/", WorkplaceCreateView.as_view(), name="workplace-create"),
    path(
        "workplaces/<int:pk>",
        WorkplaceDetailView.as_view(),
        name="workplace-detail",
    ),
    path(
        "workplaces/<int:pk>/update/",
        WorkplaceUpdateView.as_view(),
        name="workplace-update",
    ),
    path(
        "workplaces/<int:pk>/delete/",
        WorkplaceDeleteView.as_view(),
        name="workplace-delete",
    ),
    path(
        "materials/",
        MaterialListView.as_view(),
        name="material-list",
    ),
    path(
        "materials/<int:pk>/",
        MaterialDetailView.as_view(),
        name="material-detail",
    ),
    path("materials/create/", MaterialCreateView.as_view(), name="material-create"),
    path(
        "materials/<int:pk>/update/",
        MaterialUpdateView.as_view(),
        name="material-update",
    ),
    path(
        "materials/<int:pk>/delete/",
        MaterialDeleteView.as_view(),
        name="material-delete",
    ),
    path(
        "printers/",
        PrinterListView.as_view(),
        name="printer-list",
    ),
    path(
        "printers/<int:pk>/",
        PrinterDetailView.as_view(),
        name="printer-detail",
    ),
    path(
        "printers/create/",
        PrinterCreateView.as_view(),
        name="printer-create",
    ),
    path(
        "printers/<int:pk>/update/",
        PrinterUpdateView.as_view(),
        name="printer-update",
    ),
    path(
        "printers/<int:pk>/delete/",
        PrinterDeleteView.as_view(),
        name="printer-delete",
    ),
    path(
        "print-queues/",
        PrintQueueListView.as_view(),
        name="print-queue-list",
    ),
    path(
        "workplaces/<int:pk>/print-queue-create",
        PrintQueueCreateView.as_view(),
        name="print-queue-create",
    ),
    path(
        "print-queues/<int:pk>/update/",
        PrintQueueUpdateView.as_view(),
        name="print-queue-update",
    ),
    path(
        "print-queues/<int:pk>",
        PrintQueueDetailView.as_view(),
        name="print-queue-detail",
    ),
    path(
        "print-queues/<int:pk>/delete/",
        PrintQueueDeleteView.as_view(),
        name="print-queue-delete",
    ),
    path(
        "orders/<int:pk>/",
        OrderDetailView.as_view(),
        name="order-detail",
    ),
    path(
        "orders/<int:pk>/change-status",
        change_order_status,
        name="change-order-status",
    ),
    path(
        "orders/",
        OrderListView.as_view(),
        name="order-list",
    ),
    path(
        "orders/<int:pk>/delete/",
        OrderDeleteView.as_view(),
        name="order-delete",
    ),
]

app_name = "production"

wallis/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    # bild-in django authorization
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("production.urls", namespace="production")),
] + debug_toolbar_urls()

production/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models

from production.mixins import ModelAbsoluteUrlMixin
from django.conf import settings

from production.calculations import PrintQueueSummary

from production.status_objects import PrintStatusMixin, PrinterStatusMixin


class Workplace(models.Model, ModelAbsoluteUrlMixin):
    name = models.CharField(max_length=100)
    view_name = "production:workplace-detail"

    class Meta:
        ordering = ("id",)

    def __str__(self):
        return self.name


class Worker(AbstractUser, ModelAbsoluteUrlMixin):
    phone_number = models.CharField(
        max_length=13,
        null=True,
        blank=True,
        validators=[
            RegexValidator(
                regex=r"^\+380\d{9}$",
                message=(
                    "Phone number " "must be entered in the format: " "<+380999999999>!"
                ),
                code="invalid_number",
            ),
        ],
        unique=True,
    )
    workplace = models.ForeignKey(
        Workplace,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="workers",
    )
    view_name = "production:worker-detail"

    class Meta:
        ordering = ["-date_joined"]

    def __str__(self):
        return self.username


class Material(
    models.Model,
    ModelAbsoluteUrlMixin,
):
    name = models.CharField(max_length=100, unique=True)
    type = models.CharField(max_length=100)
    roll_width = models.FloatField()
    winding = models.IntegerField()
    density = models.IntegerField()
    view_name = "production:material-detail"

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["type"]


class Printer(
    PrinterStatusMixin,
    models.Model,
    ModelAbsoluteUrlMixin,
):
    status = models.CharField(
        max_length=20,
        choices=PrinterStatusMixin.STATUS_CHOICES,
        default=PrinterStatusMixin.ACTIVE,
    )
    name = models.CharField(max_length=100, unique=False)
    model = models.CharField(max_length=100, unique=True)
    materials = models.ManyToManyField(Material, related_name="printers")
    workplace = models.ForeignKey(
        Workplace,
        related_name="printers",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    view_name = "production:printer-detail"

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.full_name

    @property
    def full_name(self):
        return f"{self.name} {self.model}"


class PrintQueue(PrintStatusMixin, models.Model, ModelAbsoluteUrlMixin):
    status = models.CharField(
        max_length=50,
        choices=PrintStatusMixin.STATUS_CHOICES,
        default=PrintStatusMixin.READY_TO_PRINT,
    )
    material = models.ForeignKey(
        Material,
        on_delete=models.CASCADE,
        related_name="print_queues",
    )
    workplace = models.ForeignKey(
        Workplace,
        related_name="print_queues",
        on_delete=models.CASCADE,
    )
    creation_time = models.DateTimeField(
        auto_now_add=True,
    )
    printer = models.ForeignKey(
        Printer,
        related_name="print_queues",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    view_name = "production:print-queue-detail"

    class Meta:
        ordering = ["creation_time"]

    def __str__(self):
        return f"#{self.id}"

    @property
    def summary(self) -> PrintQueueSummary:
        orders = self.orders.all()
        return PrintQueueSummary(orders, self.material)


class Order(
    PrintStatusMixin,
    models.Model,
    ModelAbsoluteUrlMixin,
):
    status = models.CharField(
        max_length=50,
        choices=PrintStatusMixin.STATUS_CHOICES,
        default=PrintStatusMixin.READY_TO_PRINT,
    )
    code = models.CharField(
        max_length=100,
        unique=True,
        validators=[
            RegexValidator(
                regex=r"^\d+$",
                message="The code must contain only digits!",
                code="invalid_code",
            )
        ],
    )
    owner_full_name = models.CharField(max_length=255)
    manager = models.CharField(max_length=255, default="AutoCreate")
    performer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="orders",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    country_post = models.CharField(max_length=255, default="ukr-Nova Post")
    creation_time = models.DateTimeField(auto_now_add=True)
    performing_time = models.DateTimeField(null=True, blank=True)
    image_name = models.CharField(max_length=255)
    material = models.ForeignKey(
        Material, related_name="orders", on_delete=models.CASCADE
    )
    width = models.IntegerField()
    height = models.IntegerField()
    comment = models.CharField(max_length=255, blank=True, null=True)
    print_queue = models.ForeignKey(
        PrintQueue,
        related_name="orders",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    view_name = "production:order-detail"

    class Meta:
        ordering = ["creation_time"]

    def __str__(self):
        return (
            f"#{self.code} | "
            f"Material: {self.material} | "
            f"Tiles: {self.tiles_count} | "
            f"m²: {self.square_meters}"
        )

    @property
    def square_meters(self) -> float:
        return round(self.width * self.height / 10000, 2)

    @property
    def tiles_count(self) -> int:
        max_tile_width: int = 50
        segments = self.width // max_tile_width
        single_tile_width = self.width / segments

        while single_tile_width > max_tile_width:
            segments += 1
            single_tile_width = round(self.width / segments, 2)

        return segments

    @property
    def narrow_tile_width(self) -> float:
        return round((self.width / self.tiles_count) * 10, 2)

    @property
    def wide_tile_width(self) -> float:
        return self.narrow_tile_width * 2

templates/production/material_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <div class="d-flex justify-content-center">
    <h1>Delete Material: {{ material.name }}?</h1>
  </div>
  {% include "includes/delete_form.html" %}
{% endblock %}

templates/production/material_detail.html
{% extends "base.html" %}
{% block content %}
  <hr>
  <div class="d-flex justify-content-between align-items-center">
    <h1>
      Material: {{ material.name }}
    </h1>
    {% if user.is_staff %}
      <div>
        <a class="btn bg-secondary btn-sm"
           href="{% url 'production:material-update' pk=material.id %}"
           title="Edit material"
        >
          <i class="material-icons">edit</i>
        </a>
        <a class="btn btn-danger btn-sm"
           href="{% url 'production:material-delete' pk=material.id %}"
           title="Delete Material"
        >
          <i class="material-icons">delete</i>
        </a>
      </div>
    {% endif %}
  </div>
  <hr>
  <div>
    <h3>Parameters:</h3>
    <br>
    <p><strong>Type:</strong> {{ material.type }}</p>
    <p><strong>Roll width:</strong> {{ material.roll_width }}</p>
    <p><strong>Winding:</strong> {{ material.winding }}</p>
    <p><strong>Density:</strong> {{ material.density }}</p>
    <p><strong>Number of printers:</strong> {{ material.printers.count }}</p>
  </div>
  <hr>
  <br>
  <div>
    {% if material.printers.all %}
      <div class="card card-plain">
        <div class="card-header card-header-tabs card-header-success rounded">
          <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
              <div class="d-flex align-items-center justify-content-between">
                <h1 class="nav-tabs-title">Printers</h1>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="table-responsive h4">
            <table class="table">
              <thead class="text-success">
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Workplace</th>
              </tr>
              </thead>
              <tbody>
              {% for printer in material.printers.all %}
                <tr>
                  <td>{{ printer.id }}</td>
                  <td>
                    <a href="{{ printer.get_absolute_url }}"
                       class="page-link text-success"
                    >
                      {{ printer.full_name }}
                    </a>
                  </td>
                  <td>{{ printer.workplace }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    {% else %}
      <p class="text-danger"> This material is not yet assigned to any printer! </p>
    {% endif %}
  </div>
{% endblock %}

templates/production/material_list.html
{% extends "base.html" %}
{% block content %}
  {% if material_list %}
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-tabs card-header-success">
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <div class="d-flex align-items-center justify-content-between">
                  <h1 class="nav-tabs-title">Materials:</h1>
                  <ul class="nav nav-tabs" data-tabs="tabs">
                    <li class="nav-item">
                      <a class="nav-link active"
                         href="{% url 'production:material-create' %}"
                         title="Add material"
                      >
                        <i class="material-icons">add</i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="table-responsive h4">
              <table class="table">
                <thead class="text-success">
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Type</th>
                </tr>
                </thead>
                <tbody>
                {% for material in material_list %}
                  <tr>
                    <td>{{ material.id }}</td>
                    <td>
                      <a class="page-link text-success"
                         href="{% url 'production:material-detail' pk=material.id %}"
                      >
                        {{ material.name }}
                      </a>
                    </td>
                    <td>{{ material.type }}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
              {% include "includes/pagination.html" %}
            </div>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <div class="d-flex justify-content-between align-items-center">
      <h2 class="text-primary">There are no materials in the service now!</h2>
      {% if worker.id == user.id or user.is_staff %}
        <a class="btn btn-primary btn-sm"
           href="{% url 'production:material-create' %}"
           title="Add material"
        >
          <i class="material-icons">add</i>
        </a>
      {% endif %}
    </div>
  {% endif %}
{% endblock %}
{% block pagination %}
{% endblock %}

templates/production/order_detail.html
{% extends "base.html" %}
{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>
      Order: #{{ order.code }}
    </h1>
    {% if user.is_staff %}
      {% if order.is_deletable %}
        <a class="btn btn-danger btn-sm"
           href="{% url 'production:order-delete' pk=order.id %}"
           title="Delete Order"
        >
          <i class="material-icons">delete</i>
        </a>
      {% endif %}
    {% endif %}
  </div>
  <hr>
  <div>
    <h3><strong>Base information:</strong></h3>
    <table class="table">
      <tr>
        <th>Owner</th>
        <td>{{ order.owner_full_name }}</td>
      </tr>
      <tr>
        <th>Manager</th>
        <td>{{ order.manager }}</td>
      </tr>
      <tr>
        <th>Post</th>
        <td>{{ order.country_post }}</td>
      </tr>
      <tr>
        <th>Creation time</th>
        <td>{{ order.creation_time }}</td>
      </tr>
      <tr>
        <th>Comment</th>
        <td>{{ order.comment }}</td>
      </tr>
      <tr>
        <th>Status</th>
        <td>
          <div class="d-flex justify-content-between align-items-center">
            {{ order.get_status_display }}
            {% if order.is_editable %}
              <a href="{% url 'production:change-order-status' pk=order.pk %}"
                 class="btn btn-sm mr-2 {% if order.is_printable %} btn-danger {% else %} btn-primary {% endif %}">
                {% if order.is_printable %}
                  Mark as Problem
                {% else %}
                  Mark as Ready
                {% endif %}
              </a>
            {% endif %}
          </div>
        </td>
      </tr>
    </table>
  </div>
  <div>
    <h3><strong>Production details:</strong></h3>
    <table class="table">
      <tr>
        <th>Image</th>
        <td>
          <div class="d-flex justify-content-between align-items-baseline">
            {{ order.image_name }}
            <a href="#"
               class="btn btn-sm btn-success mr-2"
               title="Open image"
            >Open
            </a>
          </div>
        </td>
      </tr>
      <tr>
        <th>Material</th>
        <td>{{ order.material }}</td>
      </tr>
      <tr>
        <th>Square meters</th>
        <td>{{ order.square_meters }} m²</td>
      </tr>
      <tr>
        <th>Tiles count</th>
        <td>{{ order.tiles_count }}</td>
      </tr>
      <tr>
        <th>Wide tile width</th>
        <td>{{ order.wide_tile_width }} mm.</td>
      </tr>
      <tr>
        <th>Narrow tile width</th>
        <td>{{ order.narrow_tile_width }} mm.</td>
      </tr>
    </table>
  </div>
  <div>
    <h3><strong>Performing details:</strong></h3>
    <table class="table">
      <tr>
        <th>Print Queue</th>
        <td class="text-center">
          {% if order.print_queue %}
            <div class="d-flex justify-content-between align-items-center">
              #{{ order.print_queue.id }}
              <a class="btn btn-sm btn-warning mr-2"
                 href="{% url 'production:print-queue-detail' pk=order.print_queue.id %}"
                 title="Open print queue"
              >Open
              </a>
            </div>
          {% else %}
            {{ order.print_queue }}
          {% endif %}
        </td>
      </tr>
      <tr>
        <th>Performed by</th>
        <td class="text-center">
          {% if order.performer %}
            <a class="page-link text-primary"
               href="{% url 'production:worker-detail' pk=order.performer.id %}"
            >{{ order.performer }}
            </a>
          {% else %}
            {{ order.performer }}
          {% endif %}
        </td>
      </tr>
      <tr>
        <th>Performing time</th>
        <td class="text-center">
          {{ order.performing_time }}
        </td>
      </tr>
    </table>
  </div>
  <hr>
  <div>
    <a href="{% url 'production:order-list' %}"
       class="btn bg-inverse"
    >< Back to Order List
    </a>
  </div>
{% endblock %}

templates/production/order_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  {% if order_list %}
    {% include "includes/filter_form.html" %}
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-tabs card-header-warning">
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <div class="d-flex align-items-center justify-content-between">
                  <h1 class="nav-tabs-title">Orders:</h1>
                  <ul class="nav nav-tabs" data-tabs="tabs">
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="table-responsive h4">
              <table class="table text-center">
                <thead class="text-warning">
                <tr>
                  <th>ID</th>
                  <th>Code</th>
                  <th>Post</th>
                  <th>Material</th>
                  <th>Tiles count</th>
                  <th>Square meters</th>
                  <th>Status</th>
                </tr>
                </thead>
                <tbody>
                {% for order in order_list %}
                  <tr>
                    <td>{{ order.id }}</td>
                    <td>
                      <a class="page-link text-warning"
                         href="{% url 'production:order-detail' pk=order.id %}"
                      >{{ order.code }}</a>
                    </td>
                    <td>{{ order.country_post }}</td>
                    <td>{{ order.material.name }}</td>
                    <td>{{ order.tiles_count }}</td>
                    <td>{{ order.square_meters }} m²</td>
                    <td>{{ order.get_status_display }}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
              {% include "includes/pagination.html" %}
            </div>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <div class="d-flex justify-content-between align-items-center">
      <h2 class="text-primary">There are no orders in the service now!</h2>
    </div>
  {% endif %}
{% endblock %}
{% block pagination %}
{% endblock %}

templates/production/print_queue_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <div class="d-flex justify-content-center">
    <h1>Delete Print Queue: #{{ printqueue.id }}?</h1>
  </div>
  {% include "includes/delete_form.html" %}
{% endblock %}

templates/production/print_queue_form.html
{% extends "base.html" %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create new" }} print queue{{ object|yesno:":," }}
    {% if object %}{{ object }}{% endif %}</h1>
  {% include "includes/summary.html" %}
  {% include "includes/form.html" %}
  {% if workplace %}
    <div>
      <a class="btn btn-default"
         href="{% url 'production:workplace-detail' pk=workplace.id %}">
        < Back to Workplace
      </a>
    </div>
  {% endif %}
{% endblock %}

templates/production/print_queue_list.html
{% extends "base.html" %}
{% block content %}
  {% if printqueue_list %}
    {% include "includes/filter_form.html" %}
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-tabs card-header-warning">
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <div class="d-flex align-items-center justify-content-between">
                  <h1 class="nav-tabs-title">Print Queues:</h1>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="table-responsive h4">
              <table class="table text-center">
                <thead class="text-warning">
                <tr>
                  <th>ID</th>
                  <th>Workplace</th>
                  <th>Material</th>
                  <th>Status</th>
                  <th>Tiles Count</th>
                  <th>Square meters</th>
                  <th>Number of orders</th>
                </tr>
                </thead>
                <tbody>
                {% for printqueue in printqueue_list %}
                  <tr>
                    <td>
                      <a class="page-link text-warning"
                         href="{% url 'production:print-queue-detail' pk=printqueue.id %}"
                      >
                        {{ printqueue.id }}
                      </a>
                    </td>
                    <td>{{ printqueue.workplace }}</td>
                    <td>{{ printqueue.material }}</td>
                    <td>{{ printqueue.get_status_display }}</td>
                    <td>{{ printqueue.summary.total_tiles }}</td>
                    <td>{{ printqueue.summary.total_area }} m²</td>
                    <td>{{ printqueue.orders.count }}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
              {% include "includes/pagination.html" %}
            </div>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <h2 class="text-danger">There are no print queues in the service now!</h2>
  {% endif %}
{% endblock %}
{% block pagination %}
{% endblock %}

templates/production/printer_list.html
{% extends "base.html" %}
{% block content %}
  {% if printer_list %}
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-tabs card-header-success">
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <div class="d-flex align-items-center justify-content-between">
                  <h1 class="nav-tabs-title">Printers:</h1>
                  <ul class="nav nav-tabs" data-tabs="tabs">
                    <li class="nav-item">
                      <a class="nav-link active"
                         href="{% url 'production:printer-create' %}"
                         title="Add printer"
                      >
                        <i class="material-icons">add</i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="table-responsive h4">
              <table class="table text-center">
                <thead class="text-success">
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Status</th>
                  <th>Number of materials</th>
                  <th>Workplace</th>
                </tr>
                </thead>
                <tbody>
                {% for printer in printer_list %}
                  <tr>
                    <td>{{ printer.id }}</td>
                    <td>
                      <a class="page-link text-success"
                         href="{% url 'production:printer-detail' pk=printer.id %}"
                      >
                        {{ printer.full_name }}
                      </a>
                    </td>
                    <td>{{ printer.get_status_display }}</td>
                    <td>{{ printer.materials.count }}</td>
                    <td>{{ printer.workplace }}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
              {% include "includes/pagination.html" %}
            </div>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <div class="d-flex justify-content-between align-items-center">
      <h2 class="text-primary">There are no printers in the service now!</h2>
      {% if worker.id == user.id or user.is_staff %}
        <a class="btn btn-primary btn-sm"
           href="{% url 'production:printer-create' %}"
           title="Add printer"
        >
          <i class="material-icons">add</i>
        </a>
      {% endif %}
    </div>
  {% endif %}
{% endblock %}
{% block pagination %}
{% endblock %}

templates/production/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1> {{ object|yesno:"Update,Register new" }} worker {{ object|yesno:"profile," }}</h1>
  {% include "includes/crispy_form.html" %}
{% endblock %}

templates/production/worker_list.html
{% extends "base.html" %}
{% block content %}
  {% if worker_list %}
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-tabs card-header-primary">
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <div class="d-flex align-items-center justify-content-between">
                  <h1 class="nav-tabs-title">Workers:</h1>
                  <ul class="nav nav-tabs" data-tabs="tabs">
                    <li class="nav-item">
                      <a class="nav-link active" href="{% url 'production:worker-create' %}">
                        <i class="material-icons">add</i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="table-responsive h4">
              <table class="table">
                <thead class=" text-primary">
                <tr>
                  <th>ID</th>
                  <th>Username</th>
                  <th>First name</th>
                  <th>Last name</th>
                  <th>Phone number</th>
                  <th>Workplace</th>
                </tr>
                </thead>
                <tbody>
                {% for worker in worker_list %}
                  <tr>
                    <td>{{ worker.id }}</td>
                    <td>
                      <a href="{{ worker.get_absolute_url }}"
                         class="page-link text-primary" 
                      >
                        {{ worker.username }} 
                        {% if user == worker %}(Me){% endif %}
                      </a></td>
                    <td>{{ worker.first_name }}</td>
                    <td>{{ worker.last_name }}</td>
                    <td>{{ worker.phone_number }}</td>
                    <td>
                      {% if worker.workplace %}
                        <a class="page-link text-primary"
                          href="{% url 'production:workplace-detail' pk=worker.workplace.id %}"
                        >{{ worker.workplace }}
                        </a>
                        {% else %}
                        {{ worker.workplace }}
                      {% endif %}
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
              {% include "includes/pagination.html" %}
            </div>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <h2 class="text-primary">There are no workers in the service now!</h2>
  {% endif %}
{% endblock %}
{% block  pagination %}
{% endblock %}

templates/production/worker_phone_number_form.html
{% extends "base.html" %}
{% block content %}
  <br>
  <div>
  <h1>User: {{ user.username }}</h1>
  <br>
  </div>
{% include "includes/crispy_form.html" %}
{% endblock %}

templates/production/workplace_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <div class="d-flex justify-content-center">
    <h1>Delete Workplace: {{ workplace.name }}?</h1>
  </div>
  {% include "includes/delete_form.html" %}
{% endblock %}